[package]
name = "vauncher-core"
version = "0.1.0"
edition = "2021"
authors = ["Vitaliy Busko <vitaliy.opensource@gmail.com>"]

[dependencies]
md-5 = "0.10.1"
octocrab = "0.16.0"
tokio = "1.19"
serde = "1.0"
serde_json = "1.0"
rand = "0.8.5"
